from helper import Dimensions
from pygame import Color

WINDOW_SIZE = Dimensions(800, 400)
BACKGROUND_COLOR = Color('#000000')
BALL_COLOR = Color('#FF0000')
SCORE_COLOR = Color('#FFFFFF')

PADDLE_LENGTH = 100
PADDLE_THICKNESS = 10

PADDLE_SPEED = 400.0

BALL_RADIUS = 10
BALL_SPEED = 100.0

NET_DASH_LENGTH = 30
NET_WIDTH = 2

COUNTDOWN_BEGIN = 3
DURATION_PER_MESSAGE = 0.5  # in seconds
